# Generated by Django 2.2.2 on 2019-09-01 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.IntegerField()),
                ('name', models.CharField(max_length=36)),
                ('interest_rate', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('outbox_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=20)),
                ('msg_content_id', models.CharField(max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_time', models.DateTimeField(null=True)),
                ('ait_delivery_status', models.CharField(max_length=10, null=True)),
                ('ait_failure_reason', models.CharField(max_length=10, null=True)),
                ('ait_message_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=1)),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PhoneOtp',
            },
        ),
        migrations.CreateModel(
            name='SavingFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('duration', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving_rate', models.FloatField(default=1)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SavingFrequency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingMethodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference_number', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('recipient', models.CharField(max_length=20)),
                ('successful', models.BooleanField(default=False)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_balance', models.FloatField(default=0)),
                ('savings_balance', models.FloatField(default=0)),
                ('total_spending', models.FloatField(default=0)),
                ('saving_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SavingMethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='savingmethod',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SavingMethodType'),
        ),
        migrations.CreateModel(
            name='Loanee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Wallet')),
            ],
            options={
                'db_table': 'Loanee',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField(default=1)),
                ('period', models.FloatField(default=1)),
                ('disbursement_date', models.DateField()),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lender')),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Loanee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
