# Generated by Django 2.2.2 on 2019-09-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190902_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.CharField(default=254703456654, max_length=20),
            preserve_default=False,
        ),
    ]
