# Generated by Django 2.2.7 on 2020-04-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_time', models.TimeField()),
                ('name', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='loan',
            name='financier',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loanee',
        ),
        migrations.RemoveField(
            model_name='loanee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loanee',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Outbox',
        ),
        migrations.DeleteModel(
            name='PhoneOtp',
        ),
        migrations.RemoveField(
            model_name='savingmethod',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='savingmethod',
            name='saving_type',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='saving_method',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Loanee',
        ),
        migrations.DeleteModel(
            name='SavingFrequency',
        ),
        migrations.DeleteModel(
            name='SavingMethod',
        ),
        migrations.DeleteModel(
            name='SavingMethodType',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
